apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
spec:
  managementState: Managed
  customization:
    customLogoFile:
      key: my-logo.png
      name: console-custom-logo
    customProductName: ACS
